### PR TITLE
Fix typo in the doc of SearchableMap.js

### PR DESCRIPTION
**Pull request by graphman65**

### CODE REVIEW

**Comment by lucaong** [comment]
Hi @graphman65 , thanks for your contribution!

I am not sure the change is correct though, the previous example in the documentation was:

```javascript
let map = new SearchableMap()
map.set("unicorn", 1)
map.set("universe", 2)
map.set("university", 3)
map.set("unique", 4)
map.set("hello", 5)

let uni = map.atPrefix("uni")
uni.get("unique") // => 4
uni.get("unicorn") // => 1
uni.get("hello") // => undefined

let univer = map.atPrefix("univer")
univer.get("unique") // => undefined
univer.get("universe") // => 2
univer.get("university") // => 3
```

The last part of the example should use the `univer` variable, to show the effect of using the map `atPrefix("univer")`, as opposed to the `uni` variable using the map `atPrefix("uni")`. That's why the call to `univer.get("unique")` return `undefined` (while `uni.get("unique")` returns `4`).

Or am I mistaken?

**Comment by lucaong** [comment]
Oooooh wait, now I see, you _fixed it_ making it lok exactly as I described above. Thanks a lot and sorry for the confusion, I had a long day 😄 I will merge it now.

**Comment by lucaong** [comment]
Merged 🙂 Your contribution is mentioned in the [changelog](https://github.com/lucaong/minisearch/blob/master/CHANGELOG.md) and will be included in the next release.

**Comment by graphman65** [comment]
Ahahah no problem :slightly_smiling_face: Thanks.

**Pull request merged**
