### PR TITLE
fix(search): makes sure regexp escapes `{` and `}`

### PR DESCRIPTION
**Pull request by stalniy**
this prevents babel plugin from failing

Related issue where it should be fixed https://github.com/jviereck/regjsparser/issues/104 . But I don't know how quickly their release cycle can be especially that this may require update in babel plugin

### CODE REVIEW

**Comment by lucaong** [comment]
Thanks a lot @stalniy ! We will need to configure the linter so that it does not complain on this, but it makes sense if it breaks a very popular build tool.

Out of curiosity, what is the babel error you are encountering?

**Comment by stalniy** [comment]
I used quite not standard setup of rollup + babel. I do transpile typescript using babel + typescript into ES6 then I transpile that code to ES5 (so I have legacy build for my docs app :) and save some extra seconds) and during legacy build I encountered  the next error:

```
SyntaxError: /home/sergii/projects/casl/docs-src/bootstrap.6af6ddda.js: unescaped or unmatched closing brace at position 25
    ;?@[-\]_{}\u00A0\u00
              ^
bootstrap.6af6ddda.js
SyntaxError: /home/sergii/projects/casl/docs-src/bootstrap.6af6ddda.js: unescaped or unmatched closing brace at position 25
    ;?@[-\]_{}\u00A0\u00
              ^
    at bail (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1131:13)
    at createCharacter (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:239:11)
    at parseClassAtomNoDash (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1107:16)
    at parseClassAtom (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1096:16)
    at parseNonemptyClassRangesNoDash (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1075:17)
    at parseHelperClassRanges (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1040:13)
    at parseNonemptyClassRangesNoDash (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1086:14)
    at parseHelperClassRanges (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1040:13)
    at parseNonemptyClassRanges (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1066:14)
    at parseClassRanges (/home/sergii/projects/casl/docs-src/node_modules/regjsparser/parser.js:1010:15)
```

First I thought this is the fault of `regjsparser` package but it's not! And it's very strange that it doesn't work in this setup but your package is transpiled successfully. I tried to add this escaping chars and it worked. Looks like somewhere in the pipeline babel encounters some unsupported scenario and regexp is passed to regjsparser without proper escaping.

To fix this I used `['@babel/plugin-proposal-unicode-property-regex', { useUnicodeFlag: false }],`, probably it make sense to add this plugin to your build, so it's more safe and others won't get similar errors.

So, I guess this PR can be safely closed in favor of using `@babel/plugin-proposal-unicode-property-regex`

**Comment by lucaong** [comment]
Actually, the linter configuration is currently broken I realize (wrong paths in `package.json`). I will fix it after merging this and take care of not letting it complain about the unnecessary escape.

**Comment by lucaong** [comment]
I see, thanks for the writeup @stalniy ! I'll close this PR then, and see how to deal with this.

**Pull request closed without merging**
