### PR TITLE
Terms matching fuzzy+prefix criteria score higher than exact matches (WIP)

### PR DESCRIPTION
**Pull request by rolftimmermans**
The issue is outlined in https://github.com/lucaong/minisearch/pull/126#issuecomment-1042819909.

Added a failing test for now. I'll give some more thought about the best solution to this.

### CODE REVIEW

**Comment by rolftimmermans** [comment]
@lucaong I have a solution proposal.

In case we do fuzzy + prefix matching, both searches are executed first. If a prefix result also occurs in the fuzzy match set, we simply delete it before they are processed. This makes the assumption that a prefix match is always superior to a fuzzy match.

All results are now stored directly into the same map. This is possible because we guarantee there are no duplicates.

There is a test I had to modify to keep it passing. And I also had to change the return type of `fuzzyGet()` from an object to a Map. This is a **breaking** change. The reason is that since we delete items from the result of the call to `fuzzyGet()` a Map is a better fit conceptually (and deleting properties from an object in hot code can be a performance pitfall; JS engines generally don't like properties being deleted).

**Comment by rolftimmermans** [comment]
With the change as proposed now, search performance improves:

### Before
```
Combined search:
================
  * MiniSearch#search("virtute e conoscienza") x 165 ops/sec ±2.97% (78 runs sampled)
```

### After
```
Combined search:
================
  * MiniSearch#search("virtute e conoscienza") x 245 ops/sec ±1.79% (90 runs sampled)
```

**Comment by lucaong** [comment]
I agree that this solution is the correct one 👍 happy to see it also implies another performance improvement!

**Comment by lucaong** [comment]
I would be happy with merging this change to `fuzzyGet` without a major release. It technically is a breaking change, but I suspect nobody else than myself is using `minisearch/SearchableMap` directly.

**Pull request merged**
